# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Map.create!([
  { :name => "Turtle Rock", :is_multi => 1, :created_at => "2013-11-25 15:49:56", :updated_at => "2013-11-25 15:49:56" }
])



Message.create!([
  { :sender_id => 1, :receiver_id => 2, :is_read => false, :content => "I love you", :created_at => "2013-11-25 16:03:22", :updated_at => "2013-11-25 16:03:22" }
])



Position.create!([
  { :user_id => 1, :map_id => 1, :x => 20, :y => 40, :created_at => "2013-11-25 15:56:37", :updated_at => "2013-11-25 15:56:37" }
])



Task.create!([
  { :name => "mKiller1", :is_multi => 0, :level => 1, :map_id => 1, :status => 0, :x => nil, :y => nil, :created_at => "2013-11-25 15:56:06", :updated_at => "2013-11-25 15:56:06", :category => 0 }
])



User.create!([
  { :name => "Yue", :phoneID => 1, :age => 24, :interest => "basketball", :agility => 8, :strength => 7, :arithmatic => 6, :logic => 5, :literature => 4, :teamwork => 3, :created_at => "2013-11-25 15:46:54", :updated_at => "2013-11-25 15:46:54" },
  { :name => "Feng", :phoneID => 2, :age => 24, :interest => "Love", :agility => 1, :strength => 2, :arithmatic => 3, :logic => 4, :literature => 5, :teamwork => 6, :created_at => "2013-11-25 15:57:07", :updated_at => "2013-11-25 15:57:07" }
])


